//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Zim.Tech.TravelLiker.Travelport.uAPI.Air.witoutNS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class LowFareSearchRsp
    {

        private LowFareSearchRspResponseMessage[] responseMessageField;

        private LowFareSearchRspFlightDetailsListFlightDetails[][] flightDetailsListField;

        private LowFareSearchRspAirSegmentListAirSegment[][] airSegmentListField;

        private LowFareSearchRspFareInfoListFareInfo[][] fareInfoListField;

        private LowFareSearchRspRouteListRoute[][] routeListField;

        private LowFareSearchRspAirPricingSolution[] airPricingSolutionField;

        private string traceIdField;

        private string transactionIdField;

        private string responseTimeField;

        private string distanceUnitsField;

        private string currencyTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseMessage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public LowFareSearchRspResponseMessage[] ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FlightDetails", typeof(LowFareSearchRspFlightDetailsListFlightDetails), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LowFareSearchRspFlightDetailsListFlightDetails[][] FlightDetailsList
        {
            get
            {
                return this.flightDetailsListField;
            }
            set
            {
                this.flightDetailsListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AirSegment", typeof(LowFareSearchRspAirSegmentListAirSegment), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LowFareSearchRspAirSegmentListAirSegment[][] AirSegmentList
        {
            get
            {
                return this.airSegmentListField;
            }
            set
            {
                this.airSegmentListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FareInfo", typeof(LowFareSearchRspFareInfoListFareInfo), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LowFareSearchRspFareInfoListFareInfo[][] FareInfoList
        {
            get
            {
                return this.fareInfoListField;
            }
            set
            {
                this.fareInfoListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Route", typeof(LowFareSearchRspRouteListRoute), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LowFareSearchRspRouteListRoute[][] RouteList
        {
            get
            {
                return this.routeListField;
            }
            set
            {
                this.routeListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AirPricingSolution", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolution[] AirPricingSolution
        {
            get
            {
                return this.airPricingSolutionField;
            }
            set
            {
                this.airPricingSolutionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TraceId
        {
            get
            {
                return this.traceIdField;
            }
            set
            {
                this.traceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResponseTime
        {
            get
            {
                return this.responseTimeField;
            }
            set
            {
                this.responseTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DistanceUnits
        {
            get
            {
                return this.distanceUnitsField;
            }
            set
            {
                this.distanceUnitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrencyType
        {
            get
            {
                return this.currencyTypeField;
            }
            set
            {
                this.currencyTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspResponseMessage
    {

        private string codeField;

        private string typeField;

        private string providerCodeField;

        private string supplierCodeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProviderCode
        {
            get
            {
                return this.providerCodeField;
            }
            set
            {
                this.providerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SupplierCode
        {
            get
            {
                return this.supplierCodeField;
            }
            set
            {
                this.supplierCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspFlightDetailsListFlightDetails
    {

        private string keyField;

        private string originField;

        private string destinationField;

        private string departureTimeField;

        private string arrivalTimeField;

        private string flightTimeField;

        private string travelTimeField;

        private string equipmentField;

        private string originTerminalField;

        private string destinationTerminalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureTime
        {
            get
            {
                return this.departureTimeField;
            }
            set
            {
                this.departureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrivalTime
        {
            get
            {
                return this.arrivalTimeField;
            }
            set
            {
                this.arrivalTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightTime
        {
            get
            {
                return this.flightTimeField;
            }
            set
            {
                this.flightTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TravelTime
        {
            get
            {
                return this.travelTimeField;
            }
            set
            {
                this.travelTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Equipment
        {
            get
            {
                return this.equipmentField;
            }
            set
            {
                this.equipmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginTerminal
        {
            get
            {
                return this.originTerminalField;
            }
            set
            {
                this.originTerminalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestinationTerminal
        {
            get
            {
                return this.destinationTerminalField;
            }
            set
            {
                this.destinationTerminalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirSegmentListAirSegment
    {

        private LowFareSearchRspAirSegmentListAirSegmentAirAvailInfo[] airAvailInfoField;

        private LowFareSearchRspAirSegmentListAirSegmentFlightDetailsRef[] flightDetailsRefField;

        private string keyField;

        private string groupField;

        private string carrierField;

        private string flightNumberField;

        private string originField;

        private string destinationField;

        private string departureTimeField;

        private string arrivalTimeField;

        private string flightTimeField;

        private string distanceField;

        private string eTicketabilityField;

        private string equipmentField;

        private string changeOfPlaneField;

        private string participantLevelField;

        private string linkAvailabilityField;

        private string polledAvailabilityOptionField;

        private string optionalServicesIndicatorField;

        private string availabilitySourceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AirAvailInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirSegmentListAirSegmentAirAvailInfo[] AirAvailInfo
        {
            get
            {
                return this.airAvailInfoField;
            }
            set
            {
                this.airAvailInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FlightDetailsRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirSegmentListAirSegmentFlightDetailsRef[] FlightDetailsRef
        {
            get
            {
                return this.flightDetailsRefField;
            }
            set
            {
                this.flightDetailsRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Carrier
        {
            get
            {
                return this.carrierField;
            }
            set
            {
                this.carrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightNumber
        {
            get
            {
                return this.flightNumberField;
            }
            set
            {
                this.flightNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureTime
        {
            get
            {
                return this.departureTimeField;
            }
            set
            {
                this.departureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrivalTime
        {
            get
            {
                return this.arrivalTimeField;
            }
            set
            {
                this.arrivalTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightTime
        {
            get
            {
                return this.flightTimeField;
            }
            set
            {
                this.flightTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ETicketability
        {
            get
            {
                return this.eTicketabilityField;
            }
            set
            {
                this.eTicketabilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Equipment
        {
            get
            {
                return this.equipmentField;
            }
            set
            {
                this.equipmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChangeOfPlane
        {
            get
            {
                return this.changeOfPlaneField;
            }
            set
            {
                this.changeOfPlaneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParticipantLevel
        {
            get
            {
                return this.participantLevelField;
            }
            set
            {
                this.participantLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LinkAvailability
        {
            get
            {
                return this.linkAvailabilityField;
            }
            set
            {
                this.linkAvailabilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PolledAvailabilityOption
        {
            get
            {
                return this.polledAvailabilityOptionField;
            }
            set
            {
                this.polledAvailabilityOptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OptionalServicesIndicator
        {
            get
            {
                return this.optionalServicesIndicatorField;
            }
            set
            {
                this.optionalServicesIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AvailabilitySource
        {
            get
            {
                return this.availabilitySourceField;
            }
            set
            {
                this.availabilitySourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirSegmentListAirSegmentAirAvailInfo
    {

        private LowFareSearchRspAirSegmentListAirSegmentAirAvailInfoBookingCodeInfo[] bookingCodeInfoField;

        private string providerCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BookingCodeInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirSegmentListAirSegmentAirAvailInfoBookingCodeInfo[] BookingCodeInfo
        {
            get
            {
                return this.bookingCodeInfoField;
            }
            set
            {
                this.bookingCodeInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProviderCode
        {
            get
            {
                return this.providerCodeField;
            }
            set
            {
                this.providerCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirSegmentListAirSegmentAirAvailInfoBookingCodeInfo
    {

        private string bookingCountsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BookingCounts
        {
            get
            {
                return this.bookingCountsField;
            }
            set
            {
                this.bookingCountsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirSegmentListAirSegmentFlightDetailsRef
    {

        private string keyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspFareInfoListFareInfo
    {

        private LowFareSearchRspFareInfoListFareInfoFareSurcharge[] fareSurchargeField;

        private LowFareSearchRspFareInfoListFareInfoBaggageAllowanceMaxWeight[][] baggageAllowanceField;

        private LowFareSearchRspFareInfoListFareInfoFareRuleKey[] fareRuleKeyField;

        private string keyField;

        private string fareBasisField;

        private string passengerTypeCodeField;

        private string originField;

        private string destinationField;

        private string effectiveDateField;

        private string departureDateField;

        private string amountField;

        private string negotiatedFareField;

        private string notValidBeforeField;

        private string notValidAfterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FareSurcharge", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspFareInfoListFareInfoFareSurcharge[] FareSurcharge
        {
            get
            {
                return this.fareSurchargeField;
            }
            set
            {
                this.fareSurchargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MaxWeight", typeof(LowFareSearchRspFareInfoListFareInfoBaggageAllowanceMaxWeight), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LowFareSearchRspFareInfoListFareInfoBaggageAllowanceMaxWeight[][] BaggageAllowance
        {
            get
            {
                return this.baggageAllowanceField;
            }
            set
            {
                this.baggageAllowanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FareRuleKey", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public LowFareSearchRspFareInfoListFareInfoFareRuleKey[] FareRuleKey
        {
            get
            {
                return this.fareRuleKeyField;
            }
            set
            {
                this.fareRuleKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FareBasis
        {
            get
            {
                return this.fareBasisField;
            }
            set
            {
                this.fareBasisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PassengerTypeCode
        {
            get
            {
                return this.passengerTypeCodeField;
            }
            set
            {
                this.passengerTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureDate
        {
            get
            {
                return this.departureDateField;
            }
            set
            {
                this.departureDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NegotiatedFare
        {
            get
            {
                return this.negotiatedFareField;
            }
            set
            {
                this.negotiatedFareField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NotValidBefore
        {
            get
            {
                return this.notValidBeforeField;
            }
            set
            {
                this.notValidBeforeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NotValidAfter
        {
            get
            {
                return this.notValidAfterField;
            }
            set
            {
                this.notValidAfterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspFareInfoListFareInfoFareSurcharge
    {

        private string keyField;

        private string typeField;

        private string amountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspFareInfoListFareInfoBaggageAllowanceMaxWeight
    {

        private string valueField;

        private string unitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspFareInfoListFareInfoFareRuleKey
    {

        private string fareInfoRefField;

        private string providerCodeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FareInfoRef
        {
            get
            {
                return this.fareInfoRefField;
            }
            set
            {
                this.fareInfoRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProviderCode
        {
            get
            {
                return this.providerCodeField;
            }
            set
            {
                this.providerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspRouteListRoute
    {

        private LowFareSearchRspRouteListRouteLeg[] legField;

        private string keyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leg", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspRouteListRouteLeg[] Leg
        {
            get
            {
                return this.legField;
            }
            set
            {
                this.legField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspRouteListRouteLeg
    {

        private string keyField;

        private string groupField;

        private string originField;

        private string destinationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolution
    {

        private LowFareSearchRspAirPricingSolutionJourney[] journeyField;

        private LowFareSearchRspAirPricingSolutionLegRef[] legRefField;

        private LowFareSearchRspAirPricingSolutionAirPricingInfo[] airPricingInfoField;

        private string keyField;

        private string totalPriceField;

        private string basePriceField;

        private string approximateTotalPriceField;

        private string approximateBasePriceField;

        private string taxesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Journey", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionJourney[] Journey
        {
            get
            {
                return this.journeyField;
            }
            set
            {
                this.journeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionLegRef[] LegRef
        {
            get
            {
                return this.legRefField;
            }
            set
            {
                this.legRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AirPricingInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionAirPricingInfo[] AirPricingInfo
        {
            get
            {
                return this.airPricingInfoField;
            }
            set
            {
                this.airPricingInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalPrice
        {
            get
            {
                return this.totalPriceField;
            }
            set
            {
                this.totalPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApproximateTotalPrice
        {
            get
            {
                return this.approximateTotalPriceField;
            }
            set
            {
                this.approximateTotalPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApproximateBasePrice
        {
            get
            {
                return this.approximateBasePriceField;
            }
            set
            {
                this.approximateBasePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Taxes
        {
            get
            {
                return this.taxesField;
            }
            set
            {
                this.taxesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionJourney
    {

        private LowFareSearchRspAirPricingSolutionJourneyAirSegmentRef[] airSegmentRefField;

        private string travelTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AirSegmentRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionJourneyAirSegmentRef[] AirSegmentRef
        {
            get
            {
                return this.airSegmentRefField;
            }
            set
            {
                this.airSegmentRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TravelTime
        {
            get
            {
                return this.travelTimeField;
            }
            set
            {
                this.travelTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionJourneyAirSegmentRef
    {

        private string keyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionLegRef
    {

        private string keyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionAirPricingInfo
    {

        private string fareCalcField;

        private LowFareSearchRspAirPricingSolutionAirPricingInfoFareInfoRef[] fareInfoRefField;

        private LowFareSearchRspAirPricingSolutionAirPricingInfoBookingInfo[] bookingInfoField;

        private LowFareSearchRspAirPricingSolutionAirPricingInfoTaxInfo[] taxInfoField;

        private LowFareSearchRspAirPricingSolutionAirPricingInfoPassengerType[] passengerTypeField;

        private LowFareSearchRspAirPricingSolutionAirPricingInfoChangePenalty[] changePenaltyField;

        private LowFareSearchRspAirPricingSolutionAirPricingInfoCancelPenalty[] cancelPenaltyField;

        private string keyField;

        private string totalPriceField;

        private string basePriceField;

        private string approximateTotalPriceField;

        private string approximateBasePriceField;

        private string taxesField;

        private string latestTicketingTimeField;

        private string pricingMethodField;

        private string refundableField;

        private string eTicketabilityField;

        private string platingCarrierField;

        private string providerCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FareCalc
        {
            get
            {
                return this.fareCalcField;
            }
            set
            {
                this.fareCalcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FareInfoRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionAirPricingInfoFareInfoRef[] FareInfoRef
        {
            get
            {
                return this.fareInfoRefField;
            }
            set
            {
                this.fareInfoRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BookingInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionAirPricingInfoBookingInfo[] BookingInfo
        {
            get
            {
                return this.bookingInfoField;
            }
            set
            {
                this.bookingInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionAirPricingInfoTaxInfo[] TaxInfo
        {
            get
            {
                return this.taxInfoField;
            }
            set
            {
                this.taxInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PassengerType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionAirPricingInfoPassengerType[] PassengerType
        {
            get
            {
                return this.passengerTypeField;
            }
            set
            {
                this.passengerTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChangePenalty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionAirPricingInfoChangePenalty[] ChangePenalty
        {
            get
            {
                return this.changePenaltyField;
            }
            set
            {
                this.changePenaltyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CancelPenalty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LowFareSearchRspAirPricingSolutionAirPricingInfoCancelPenalty[] CancelPenalty
        {
            get
            {
                return this.cancelPenaltyField;
            }
            set
            {
                this.cancelPenaltyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalPrice
        {
            get
            {
                return this.totalPriceField;
            }
            set
            {
                this.totalPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApproximateTotalPrice
        {
            get
            {
                return this.approximateTotalPriceField;
            }
            set
            {
                this.approximateTotalPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApproximateBasePrice
        {
            get
            {
                return this.approximateBasePriceField;
            }
            set
            {
                this.approximateBasePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Taxes
        {
            get
            {
                return this.taxesField;
            }
            set
            {
                this.taxesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LatestTicketingTime
        {
            get
            {
                return this.latestTicketingTimeField;
            }
            set
            {
                this.latestTicketingTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PricingMethod
        {
            get
            {
                return this.pricingMethodField;
            }
            set
            {
                this.pricingMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Refundable
        {
            get
            {
                return this.refundableField;
            }
            set
            {
                this.refundableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ETicketability
        {
            get
            {
                return this.eTicketabilityField;
            }
            set
            {
                this.eTicketabilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlatingCarrier
        {
            get
            {
                return this.platingCarrierField;
            }
            set
            {
                this.platingCarrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProviderCode
        {
            get
            {
                return this.providerCodeField;
            }
            set
            {
                this.providerCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionAirPricingInfoFareInfoRef
    {

        private string keyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionAirPricingInfoBookingInfo
    {

        private string bookingCodeField;

        private string cabinClassField;

        private string fareInfoRefField;

        private string segmentRefField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BookingCode
        {
            get
            {
                return this.bookingCodeField;
            }
            set
            {
                this.bookingCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CabinClass
        {
            get
            {
                return this.cabinClassField;
            }
            set
            {
                this.cabinClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FareInfoRef
        {
            get
            {
                return this.fareInfoRefField;
            }
            set
            {
                this.fareInfoRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SegmentRef
        {
            get
            {
                return this.segmentRefField;
            }
            set
            {
                this.segmentRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionAirPricingInfoTaxInfo
    {

        private string categoryField;

        private string amountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionAirPricingInfoPassengerType
    {

        private string codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionAirPricingInfoChangePenalty
    {

        private string amountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LowFareSearchRspAirPricingSolutionAirPricingInfoCancelPenalty
    {

        private string amountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private LowFareSearchRsp[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LowFareSearchRsp")]
        public LowFareSearchRsp[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}